# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 17:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.IntegerField()),
                ('node_version', models.IntegerField()),
                ('pump_id', models.IntegerField()),
                ('pump_type', models.CharField(max_length=200)),
                ('fluid_type', models.CharField(max_length=200)),
                ('packing_model', models.CharField(max_length=200)),
                ('packing_location', models.CharField(max_length=200)),
                ('entry_date_time', models.DateTimeField(verbose_name='Date Published')),
            ],
        ),
        migrations.CreateModel(
            name='Nodeowner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_owner_id', models.IntegerField()),
                ('owner_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='node',
            name='nodeowner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metadata.Nodeowner'),
        ),
    ]
