# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='node_name',
            field=models.CharField(default='pump', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='node',
            name='pump_type',
            field=models.CharField(default='Pump', max_length=200),
        ),
    ]
