# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0002_auto_20160328_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestDatapoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_id', models.IntegerField()),
                ('data_name', models.CharField(max_length=200)),
                ('temperature', models.FloatField()),
                ('rpm', models.IntegerField()),
            ],
        ),
    ]
