# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 17:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0004_auto_20160330_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='node_deploy_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 30, 17, 37, 28, 892564, tzinfo=utc), verbose_name='Node Deploy Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='node',
            name='node_install_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 30, 17, 37, 37, 953226, tzinfo=utc), verbose_name='Node Install Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='node',
            name='sleeve_install_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 30, 17, 37, 42, 160258, tzinfo=utc), verbose_name='Install Date'),
            preserve_default=False,
        ),
    ]
